### ISSUE TITLE
Mobile Menu Morphological Chart

### ISSUE THREAD

**Issue by latoyaln** [latoyaln/wogo-DRY#5]
- [ ] Maak variaties voor jouw component met behulp van een morphological chart

**Comment by Seijno** [comment]
## Issue omschrijving
Maak voor het mobile menu een Morphological Chart.

Hier maak ik verschillende designs voor de open icon, sluit icon en de animaties richting de content.

Inspiraties heb ik gevonden in: Pinterest & andere sites voor voorbeelden.

## Resultaat
![Image](https://github.com/user-attachments/assets/12c150c3-cf0c-45d1-a198-da8687105c26)
zie [hier](https://www.figma.com/design/gYL3hoJ4L503rriYsgxPv1/Untitled?node-id=0-1&node-type=canvas&t=mfZ7SNWb0scmxloR-0)
